# Generated by Django 5.2.8 on 2025-11-22 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("anomaly_type", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "model_confidence",
                    models.FloatField(
                        help_text="Confidence score from the ML model (0–1)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomaly Event",
                "verbose_name_plural": "Anomaly Events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AgentRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("recommended_action", models.CharField(max_length=255)),
                ("explanation_text", models.TextField()),
                (
                    "confidence",
                    models.FloatField(help_text="Confidence score of the agent (0–1)"),
                ),
                (
                    "anomaly_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="monitoring.anomalyevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Recommendation",
                "verbose_name_plural": "Agent Recommendations",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FarmProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                (
                    "size",
                    models.FloatField(
                        help_text="Farm size in hectares (or chosen unit)"
                    ),
                ),
                ("crop_type", models.CharField(max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Farm Profile",
                "verbose_name_plural": "Farm Profiles",
                "ordering": ["owner_id", "location"],
            },
        ),
        migrations.CreateModel(
            name="FieldPlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_variety", models.CharField(max_length=100)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plots",
                        to="monitoring.farmprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Plot",
                "verbose_name_plural": "Field Plots",
                "ordering": ["farm_id", "id"],
            },
        ),
        migrations.AddField(
            model_name="anomalyevent",
            name="plot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomalies",
                to="monitoring.fieldplot",
            ),
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("moisture", "Soil moisture"),
                            ("temperature", "Air temperature"),
                            ("humidity", "Humidity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "source",
                    models.CharField(
                        default="simulator",
                        help_text="Source of the data (e.g., simulator)",
                        max_length=50,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_readings",
                        to="monitoring.fieldplot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor Reading",
                "verbose_name_plural": "Sensor Readings",
                "ordering": ["-timestamp"],
            },
        ),
    ]
